version: "3.8"
services:
  redis:
    image: redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend_stock_trading
    volumes:
      - ./backend_stock_trading:/app/backend_stock_trading
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend_stock_trading
    volumes:
      - ./backend_stock_trading:/app/backend_stock_trading
    command: celery -A backend_stock_trading worker --loglevel=info --pool=gevent
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
